apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse-monitor
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: clickhouse
  namespaceSelector:
    matchNames:
      - clickhouse
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s