apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: clickhouse-alerts
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  groups:
  - name: clickhouse.rules
    rules:

#01-tested
    - alert: ClickhouseMemoryUsageCritical
      expr: ClickHouseAsyncMetrics_CGroupMemoryUsed / ClickHouseAsyncMetrics_CGroupMemoryTotal * 100 > 30
      for: 1m
      labels:
        severity: critical
        team: clickhouse
      annotations:
        summary: ClickHouse Memory Usage Critical (instance {{ $labels.instance }})
        description: |
          Memory usage is critically high, over 30%.

          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"




#02-tested
    - alert: ClickhouseMemoryUsageWarning
      expr: ClickHouseAsyncMetrics_CGroupMemoryUsed / ClickHouseAsyncMetrics_CGroupMemoryTotal * 100 > 25
      for: 1m
      labels:
        severity: warning
        team: clickhouse
      annotations:
        summary: ClickHouse Memory Usage Warning (instance {{ $labels.instance }})
        description: |
          Memory usage is over 25%.

          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"

#03-tested
    - alert: ClickhouseDiskSpaceLowOnDefault
      expr: ClickHouseAsyncMetrics_DiskAvailable_default / (ClickHouseAsyncMetrics_DiskAvailable_default + ClickHouseAsyncMetrics_DiskUsed_default) * 100 < 80
      for: 1m
      labels:
        severity: warning
        team: clickhouse
      annotations:
        summary: ClickHouse Disk Space Low on Default (instance {{ $labels.instance }})
        description: |
          Disk space on default is below 80%.

          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"

#04-tested
    - alert: ClickhouseDiskSpaceCriticalOnDefault
      expr: ClickHouseAsyncMetrics_DiskAvailable_default / (ClickHouseAsyncMetrics_DiskAvailable_default + ClickHouseAsyncMetrics_DiskUsed_default) * 100 < 75
      for: 1m
      labels:
        severity: critical
        team: clickhouse
      annotations:
        summary: ClickHouse Disk Space Critical on Default (instance {{ $labels.instance }})
        description: |
          Disk space on default disk is critically low, below 75%.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"

#05-tested
    - alert: ClickhouseDiskSpaceLowOnBackups
      expr: ClickHouseAsyncMetrics_DiskAvailable_backups / (ClickHouseAsyncMetrics_DiskAvailable_backups + ClickHouseAsyncMetrics_DiskUsed_backups) * 100 < 80
      for: 1m
      labels:
        severity: warning
        team: clickhouse
      annotations:
        summary: ClickHouse Disk Space Low on Backups (instance {{ $labels.instance }})
        description:  |
         Disk space on backups is below 80%.
         
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"

#06-not working
    - alert: ClickhouseReplicaErrors
      expr: ClickHouseErrorMetric_ALL_REPLICAS_ARE_STALE == 1 or ClickHouseErrorMetric_ALL_REPLICAS_LOST == 1
      for: 0m
      labels:
        severity: critical
        team: clickhouse
      annotations:
        summary: ClickHouse Replica Errors (instance {{ $labels.instance }})
        description: |
         Critical replica errors detected, either all replicas are stale or lost.
         
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"

    #7
    - alert: ClickhouseNoAvailableReplicas
      expr: ClickHouseErrorMetric_NO_AVAILABLE_REPLICA == 1
      for: 0m
      labels:
        severity: critical
        team: clickhouse
      annotations:
        summary: ClickHouse No Available Replicas (instance {{ $labels.instance }})
        description: |
         No available replicas in ClickHouse.
         
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"


    #8
    - alert: ClickhouseNoLiveReplicas
      expr: ClickHouseErrorMetric_TOO_FEW_LIVE_REPLICAS == 1
      for: 0m
      labels:
        severity: critical
        team: clickhouse
      annotations: 
        summary: ClickHouse No Live Replicas (instance {{ $labels.instance }})
        description: |
          There are too few live replicas available, risking data loss and service disruption.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"


    #9
    # Please replace the threshold with an appropriate value
    - alert: ClickhouseHighNetworkTraffic
      expr: ClickHouseMetrics_NetworkSend > 250 or ClickHouseMetrics_NetworkReceive > 250
      for: 5m
      labels:
        severity: warning
        team: clickhouse
      annotations:
        summary: ClickHouse High Network Traffic (instance {{ $labels.instance }})
        description: |
          Network traffic is unusually high, may affect cluster performance.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"


    #10
    # Please replace the threshold with an appropriate value
    - alert: ClickhouseHighTcpConnections
      expr: ClickHouseMetrics_TCPConnection > 400
      for: 5m
      labels:
        severity: warning
        team: clickhouse
      annotations:
        summary: ClickHouse High TCP Connections (instance {{ $labels.instance }})
        description: |
          High number of TCP connections, indicating heavy client or inter-cluster communication.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"


    #11
    - alert: ClickhouseInterserverConnectionIssues
      expr: increase(ClickHouseMetrics_InterserverConnection[5m]) > 0
      for: 1m
      labels:
        severity: warning
        team: clickhouse
      annotations:
        summary: ClickHouse Interserver Connection Issues (instance {{ $labels.instance }})
        description: |
          An increase in interserver connections may indicate replication or distributed query handling issues.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"



    #12
    - alert: ClickhouseZookeeperConnectionIssues
      expr: avg(ClickHouseMetrics_ZooKeeperSession) != 1
      for: 3m
      labels:
        severity: warning
        team: clickhouse
      annotations:
        summary: ClickHouse ZooKeeper Connection Issues (instance {{ $labels.instance }})
        description: |
          ClickHouse is experiencing issues with ZooKeeper connections, which may affect cluster state and coordination.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"



    #13
    - alert: ClickhouseAuthenticationFailures
      expr: increase(ClickHouseErrorMetric_AUTHENTICATION_FAILED[5m]) > 0
      for: 0m
      labels:
        severity: info
        team: clickhouse
      annotations:
        summary: ClickHouse Authentication Failures (instance {{ $labels.instance }})
        description: |
          Authentication failures detected, indicating potential security issues or misconfiguration.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"



    #14
    - alert: ClickhouseAccessDeniedErrors
      expr: increase(ClickHouseErrorMetric_RESOURCE_ACCESS_DENIED[5m]) > 0
      for: 0m
      labels:
        severity: info
        team: clickhouse
      annotations:
        summary: ClickHouse Access Denied Errors (instance {{ $labels.instance }})
        description: |
          Access denied errors have been logged, which could indicate permission issues or unauthorized access attempts.
          
          Value: {{ printf "%.2f" $value }}

          Labels:
          {{- range $k, $v := $labels }}
            • {{ $k }}: {{ $v }}
          {{- end }}
        runbook_url: "https://www.nobl9.com/it-incident-management/runbook-example"
        dashboard_url: "http://localhost:3000/d/thEkJB_Mz/clickhouse-dash?orgId=1&from=now-15m&to=now&timezone=browser&var-datasource=prometheus&var-instance=$__all&var-trends=1&var-peaks=null&refresh=30s"